[package]
name = "boli"
version = "0.8.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "14.0.0"
assert_cmd = "2.0.14"

[dependencies.clap]
version = "4"
features = ["derive", "cargo"]
